name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli

    - name: Check if bucket exists
      run: |
        aws --version
        if aws s3api head-bucket --bucket ${{ env.AWS_BUCKET_NAME }}; then
          echo "Bucket exists."
        else
          echo "Bucket does not exist. Stopping the pipeline."
          exit 1
        fi

    - name: Deploy to AWS S3 - tpmydeployment
      if: success()
      run: |
        ls -la
        aws s3 sync . s3://tpmydeployment --delete --exclude ".git/*" --exclude ".github/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ env.AWS_BUCKET_NAME }}

